# default: &default
#   adapter: postgres
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: luca
#   password: ciccone
#   host: localhost
# # default: &default
# #   adapter: postgres
# #   encoding: utf8
# #   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
# #   username: glory
# #   password: montreal
# #   host: localhost

#  development:
#    <<: *default
#    database: postgres
host: ls-c753c3308c0d4d7b96bc0dddfd5a25beb9a8e87c.crydppxblqbm.ca-central-1.rds.amazonaws.com
port: 5432
login: academy
password: !inMgoR&04mm1+x