default: &default
  adapter: postgres
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mynewpassword
  host: localhost

development:
  <<: *default
  database: postgres
